#!/usr/bin/env python

import requests
from logging import getLogger, Logger, StreamHandler, DEBUG
from requests.sessions import Session
from requests.adapters import HTTPAdapter, Retry
from json import loads, dumps

from typing import Dict, List, Any

logger: Logger = getLogger()
logger.propagate = True
logger.addHandler(StreamHandler())
logger.setLevel(DEBUG)


def create_requests_session(headers: Dict[str, str] = dict()) -> Session:
    session: Session = requests.session()
    session.headers.update(headers)
    retry = Retry(total=10, backoff_factor=0.5)
    adapter = HTTPAdapter(max_retries=retry)
    session.mount(f"http", adapter)
    return session


def get_input_data() -> Dict[str, Any]:
    return loads(input())


def main() -> None:
    source_data: Dict[str, Any] = get_input_data()
    logger.debug(dumps(source_data, indent=2))
    requests_session: Session = create_requests_session(
        {"Authorization": f"Bearer {source_data['source']['artifactory_token']}"}
    )
    response = requests_session.get(
        f"{source_data['source']['artifactory_url']}/artifactory/api/storage/{source_data['source']['artifactory_repo']}/{source_data['source']['artifactory_path']}"
    )
    response_data: Dict[str, Any] = response.json()
    logger.debug(dumps(response_data, indent=2))
    versions: List[str] = [
        release["uri"]
        for release in filter(lambda r: not r["folder"], response_data["children"])
    ]
    try:
        current_version: str = source_data["version"]["uri"]
    except KeyError as _:
        current_version: str = str()
    if current_version == versions[-1]:
        print(dumps([{"uri": current_version}]))
    else:
        print(dumps([{"uri": version} for version in versions]))


if __name__ == "__main__":
    main()
